version: '3'

services:

  reverse-proxy:
    build: ./reverse_proxy
  
  client:
    environment:
      - NODE_ENV=production
    volumes:
      - ./client:/app
    # restart: always
    command: yarn start

  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend/:/app/
    restart: always
    ports:
      - 5678:5678
    command: ["gunicorn", "--workers=1", "app.main:app"]