version: '3'

services:

  reverse-proxy:
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  
  client:
    stdin_open: true
    volumes:
      - ./client:/app
    environment:
      - NODE_ENV=development
    command: yarn start

  backend:
    volumes:
      - ./backend/:/app/
    ports:
      - 5678:5678
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--log-level", "debug", "--port", "8000", "--reload"]