version: '3'

services:

  reverse-proxy:
    build: ./reverse_proxy
    container_name: reverse_proxy
    depends_on:
      - client
      - backend
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  
  client:
    stdin_open: true
    build: ./client
    container_name: client
    command: yarn start
    depends_on:
      - backend
    volumes:
      - ./client:/app
    environment:
      - NODE_ENV=development
    restart: on-failure

  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend/:/app/
    restart: on-failure