version: '3'

services:

  reverse-proxy:
    build: ./reverse_proxy
    depends_on:
      - client
      - backend
  
  client:
    build: ./client
    depends_on:
      - backend

  backend:
    build: ./backend